#!/bin/csh -f

# Make symlinks to the executabels in in the globals bin directory.
# For removing them, see ./DEINSTALL

set PROGS = (Treebank_tokenization.sed \
             mxpost \
             mxpost.jar \
             mxterminator \
             tagger.project \
             trainmxpost \
             trainmxterminator )


set GLOBAL_BIN = /group/contrib/nlp-speech/bin
set LOCAL_BIN  = `pwd`

cd $GLOBAL_BIN
foreach f ($PROGS)
    ln -s $LOCAL_BIN/$f
end
