#!/bin/ksh

export CLASSPATH=/group/project/nlp-speech/src/mxpost/mxpost.jar

if [ $# != 1 ]
	then
	print -u2 "Usage: $0 <projectdir>"
	print -u2 "\n\nAn example for a project dir is"
	print -u2 "\n/group/project/nlp-speech/src/mxpost/tagger.project"
	exit 1
fi


java -mx30m tagger.TestTagger $1
